openapi: 3.1.0
info:
  title: Arcturus Stellar Plugin
  summary: A server to get access to Stellar Network and Soroban Data.
  description: An API that allows the user to request information about accounts and their payments from the Stellar Network (Blockchain).  An account is identified by it's account id. If you do not know the account id ask the user for it. Accounts can optionally have a domain associated with them, which links to off-chain matadata about the account and organization that owns the account. When loading the account details and a domain is associated with the account, ask the user if she would also like to also load the off-chain metadata. Furthermore claimable balances can belong to an account. The account can be claimant or sponsor of a claimable balance. Accounts on the Stellar network can be used to track, hold, and transfer any type of asset. Each asset, except the native Stellar Lumens, has an issuer which is also an Stellar account. The user can also request payments associated with an account. Payments are part of the transaction wich can also be loaded. The transaction contains relevant info about the payment such as the memo used. Due to context window limit of ChatGPT, the endpoints that load payments or claimable balances are limited to 2 records per request. It is important to let the user know that you can load only 2 at once and that there may be more available. If the user wants more at once you have to make multiple requests. 
  version: 0.0.1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  contact:
    name: Arcturus Support
    url: https://soneso.com
    email: hi@soneso.com
servers:
  - url: http://localhost:5003